HL7-DaVinci/test-ehr

fhirResourcesToLoad/o2billy_03__condition.json, fhirResourcesToLoad/o2billy_03__conditionB.json, fhirResourcesToLoad/o2billy_03__conditionC.json, fhirResourcesToLoad/o2jane_03__condition.json, fhirResourcesToLoad/o2jane_03__conditionB.json, fhirResourcesToLoad/o2jane_03__conditionC.json, fhirResourcesToLoad/o2john_03__condition.json, fhirResourcesToLoad/o2john_03__conditionB.json, fhirResourcesToLoad/o2john_03__conditionC.json, fhirResourcesToLoad/o2john_03__observation.json, fhirResourcesToLoad/o2teddy_03__condition.json, fhirResourcesToLoad/o2teddy_03__conditionB.json, fhirResourcesToLoad/o2teddy_03__conditionC.json
Updated condition clinicalStatus and verificationStatus to go from code to CodableConcept type.
Changed one observation to be in relevant time period for oxygen therapy.
=> Fix codes in R4 Condition resource test data

fhirResourcesToLoad/o2teddy_05_device-request-cpap-e0470.json, fhirResourcesToLoad/o2teddy_05_device-request-cpap-e0601.json
https://jira.mitre.org/browse/DMEERX-377
Convert CQL rules in CRD to real PAP rules - maintain STU 3 support
1. Add test data for E0470 and E0601 in R4 branch
=> add test data for PAP devices

fhirResourcesToLoad/o2teddy_05_device-request_cpap_e0601.json, fhirResourcesToLoad/o2teddy_05_device-request_cpap_e470.json
Add test data for E0470 and E0601 for STU3 branch
=> add pap rules for stu3 branch

fhirResourcesToLoad/o2teddy_06_service-request-neat-A0426.json
Create test data for NEAT service request A0426
=> Neatcrdrules

fhirResourcesToLoad/o2teddy_06_service-request-neat-A0426.json
Fix the performer to be an array.
=> fix the performer data

fhirResourcesToLoad/o2billy_03__observation_oxygen_pao2.json, fhirResourcesToLoad/o2billy_03__observation_oxygenexercise.json, fhirResourcesToLoad/o2billy_03__observation_oxygenpp.json, fhirResourcesToLoad/o2billy_03__observation_oxygensaturation.json, fhirResourcesToLoad/o2billy_04__device-request.json
Add test data for oxygen therapy.
=> Himss branch 2020

fhirResourcesToLoad/o2jane_03__condition_36485005.json
=> DMEERX-427 ventilator

build.gradle, fhirResourcesToLoad/Practitioner_strange.json, fhirResourcesToLoad/o2teddy_03__conditionC.json, fhirResourcesToLoad/o2teddy_03__encounter_cold.json, fhirResourcesToLoad/o2teddy_03__encounter_heartfailure.json, fhirResourcesToLoad/o2teddy_03__encounter_heartfailure_before6months.json, fhirResourcesToLoad/o2teddy_03__observationBodyWeight.json
Add test data for hospital bed dtr rules.
=> Hbdtrrules

fhirResourcesToLoad/o2billy_04__device-request.json
remove use of repeat.when. use text of code instead
=> Oxygen devicereq occurenceTiming to use code.text for device use frequency

fhirResourcesToLoad/o2billy_04_device-request-rad-E0470.json
Device request for RAD.  This is required to test RAD rule set
=> device request for RAD (E0470)

fhirResourcesToLoad/o2teddy_allergy.json, fhirResourcesToLoad/o2teddy_observation_ahi.json, fhirResourcesToLoad/o2teddy_observation_rdi.json
This PR has the test data for PAP face to face encounter PR.
=> add ahi rdi and allergy

fhirResourcesToLoad/o2jane_03__allergy_7980.json
Add AllergyIntolerance resource for progress note
=> 591 Ventilator Progress Note

fhirResourcesToLoad/o2teddy_allergy_drug.json
=> add drug allergy

fhirResourcesToLoad/medication_azathioprine.json, fhirResourcesToLoad/o2teddy_medicationrequest.json
This PR added test data for pat014.
=> DMEERX-668 CRD Rule for Immunosuppressive Drugs

fhirResourcesToLoad/o2jane_04__service-request-a4217.json
Create ServiceRequest for Urological Supplies
=> Add Urological Supplies service request

fhirResourcesToLoad/o2teddy_condition_livertransplant.json, fhirResourcesToLoad/o2teddy_procedure_kidney.json
This PR adds test data for Immunosuppressive Drugs order and dispense form.
=> DMEERX-669 Immunosuppressive Drugs Order and Dispense Form

fhirResourcesToLoad/o2jane_04__device-requestB.json, fhirResourcesToLoad/o2john_04__device-requestC.json
Fix the device requests which were using CPT code.
=> Using HCPCS code for Home Blood Glucose Monitor Topic

fhirResourcesToLoad/o2billy_04_service-request-homehealthservices-G0180.json
add home health service request to william oster
=> Home health services

fhirResourcesToLoad/7. device-request.json, fhirResourcesToLoad/o2billy_04__device-request-hb-e0250.json, fhirResourcesToLoad/o2billy_04__device-request.json, fhirResourcesToLoad/o2billy_04_device-request-rad-E0470.json, fhirResourcesToLoad/o2jane_04__device-request.json, fhirResourcesToLoad/o2jane_04__device-requestB.json, fhirResourcesToLoad/o2jane_04__device-request_e0465.json, fhirResourcesToLoad/o2john_04__device-request.json, fhirResourcesToLoad/o2john_04__device-requestB.json, fhirResourcesToLoad/o2john_04__device-requestC.json, fhirResourcesToLoad/o2john_04__device-request_hb.json, fhirResourcesToLoad/o2teddy_05__device-request.json, fhirResourcesToLoad/o2teddy_05_device-request-cpap-e0470.json, fhirResourcesToLoad/o2teddy_05_device-request-cpap-e0601.json, fhirResourcesToLoad/o2teddy_05_device-request-hb-e0250.json, fhirResourcesToLoad/o2teddy_medicationrequest.json, fhirResourcesToLoad/tbobby-device_request-hb-e0250.json
Updated the extension URL for Device-Request FHIR resources
=> Dmeerx 694 fix ext insurance extension url in test ehr

fhirResourcesToLoad/1. practitioner.json, fhirResourcesToLoad/o2teddy_04__practitioner.json
Add email addresses for two practitioner resources
=> Add practitioner's email address

fhirResourcesToLoad/Practitioner-Fairchild.json, fhirResourcesToLoad/o2billy_04_service-request-homehealthservices-G0180.json, fhirResourcesToLoad/o2teddy_careplan_hhs.json, fhirResourcesToLoad/o2teddy_careteam_hhs.json, fhirResourcesToLoad/o2teddy_clinicalimpression_hhs.json, fhirResourcesToLoad/o2teddy_condition_stroke.json, fhirResourcesToLoad/o2teddy_consent.json, fhirResourcesToLoad/o2teddy_encounter_hhs.json, fhirResourcesToLoad/o2teddy_goal_hhs_careplan.json, fhirResourcesToLoad/o2teddy_medicationstatement_azathio.json, fhirResourcesToLoad/o2teddy_provenance_hhs.json, fhirResourcesToLoad/o2teddy_servicerequest_hhs.json
This PR contains the test data for the plan of care for HHS.
=> DMEERX-567 DTR rule set for Plan of Care For Home Health Service

build.gradle, fhirResourcesToLoad/o2teddy_05_device-request-cpap-e0601.json, fhirResourcesToLoad/o2teddy_condition_osa.json, fhirResourcesToLoad/o2teddy_encounter_cpape0601.json, fhirResourcesToLoad/o2teddy_observation_ahi.json, fhirResourcesToLoad/o2teddy_observation_rdi.json
This PR adds and modifies the test data for CPAP DTR rule sets.
=> DMEERX-716 CPAP Refactor

fhirResourcesToLoad/o2billy_01__patient.json, fhirResourcesToLoad/o2teddy_04__practitioner.json
support features in Home Health Services forms
=> add phone extension to practitioner/pra1255

fhirResourcesToLoad/o2jane_04__device-request-a4217.json, fhirResourcesToLoad/o2jane_04__service-request-g0155.json, src/main/resources/fhirServer.properties
This is the pull request for changing the service request to device request for urological supplies.
=> Urological supplies order

fhirResourcesToLoad/o2teddy_condition_shoulder-fracture-open-for-NEAT.json
DMEERX-788 Review and Confirm: Qualifying Diagnosis Pre-Population
Added a condition for the patient Theodor Roosevelt to test the pre-population code for NEAT Order
=> Add condition for testing NEAT Order

build.gradle, bundlefile/PASExample.json
To load the test data, run the following command:
gradle loadBundleResource
=> DMEERX-794 Mettles Solution Rule Set

fhirResourcesToLoad/o2billy_04__device-request-hb-e0250.json, fhirResourcesToLoad/o2billy_04__device-request.json, fhirResourcesToLoad/o2billy_04_device-request-rad-E0470.json, fhirResourcesToLoad/o2jane_04__device-request-a4217.json, fhirResourcesToLoad/o2jane_04__device-request.json, fhirResourcesToLoad/o2jane_04__device-requestB.json, fhirResourcesToLoad/o2jane_04__device-request_e0465.json, fhirResourcesToLoad/o2john_04__device-request.json, fhirResourcesToLoad/o2john_04__device-requestB.json, fhirResourcesToLoad/o2john_04__device-requestC.json, fhirResourcesToLoad/o2john_04__device-request_hb.json, fhirResourcesToLoad/o2teddy_05__device-request.json, fhirResourcesToLoad/o2teddy_05_device-request-cpap-e0470.json, fhirResourcesToLoad/o2teddy_05_device-request-cpap-e0601.json, fhirResourcesToLoad/o2teddy_05_device-request-hb-e0250.json, fhirResourcesToLoad/o2teddy_medicationrequest.json, fhirResourcesToLoad/tbobby-device_request-hb-e0250.json
This PR addresses the JIRA ticket: https://jira.mitre.org/browse/DMEERX-819
=> DMEERX-819 Fix ext-insurance usage

fhirResourcesToLoad/o2teddy_medicationstatement_tylenol.json
This PR adds test data for pat014 to test repeatable table pre-population for Medication in Subjective sub-questionnaire. 
See https://github.com/HL7-DaVinci/dtr/pull/121 for the instruction to test.
=> DMEERX-778 Handling repeatable groups

src/main/java/ca/uhn/fhir/jpa/starter/JpaRestfulServer.java, src/main/java/org/hl7/davinci/ehrserver/authproxy/AuthProxy.java, src/main/java/org/hl7/davinci/ehrserver/authproxy/AuthResponse.java, src/main/java/org/hl7/davinci/ehrserver/authproxy/TokenResponse.java, src/main/resources/fhirServer.properties
Update TokenResponse to rename patient to patientId as it should be.
Need to coordinate this with the crd-request-generator and dtr fixes.
=> Logica Fix

fhirResourcesToLoad/3. patient.json, fhirResourcesToLoad/o2billy_01__patient.json, fhirResourcesToLoad/o2jane_01__patient.json, fhirResourcesToLoad/o2john_01__patient.json, fhirResourcesToLoad/o2teddy_01__patient.json
Update all patient IDs so they'll appear first in alphabet order with lots of other patients when sorted by identifier.
=> Update all patient IDs

fhirResourcesToLoad/medication_methotrexate.json, fhirResourcesToLoad/o2teddy_medicationrequest_methotrexate.json, fhirResourcesToLoad/o2teddy_medicationstatement_methotrexate.json
Add resources needed to support medication interactions with immunosuppressive drugs and the order-select hook.
=> Resources needed to support order-select hook drug-drug interactions.

src/main/resources/ClientFhirServerRealm.json
Update the KeyCloak auth realm to work with newer versions of keycloak that require the scope to be specified.
=> Support newer versions of Keycloak
